# Generated by Django 5.0 on 2023-12-20 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("available_cities", "0001_initial"),
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="client_order_id",
        ),
        migrations.AddField(
            model_name="client",
            name="arrival_city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_arrival_city",
                to="available_cities.availablecities",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="departure_city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_departure_city",
                to="available_cities.availablecities",
            ),
        ),
        migrations.DeleteModel(
            name="ClientOrder",
        ),
    ]
