# Generated by Django 5.0 on 2023-12-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_remove_client_client_order_id_client_arrival_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="telegram_id",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
