# Generated by Django 5.0 on 2023-12-20 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("available_cities", "0001_initial"),
        ("client", "0003_alter_client_email_alter_client_telegram_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="departure_city",
        ),
        migrations.AddField(
            model_name="client",
            name="arrival_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="departure_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="arrival_city",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_arrival_city",
                to="available_cities.availablecities",
            ),
        ),
    ]
