# Generated by Django 5.0 on 2023-12-20 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("available_cities", "0001_initial"),
        ("client", "0004_remove_client_departure_city_client_arrival_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="departure_city",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_departure_city",
                to="available_cities.availablecities",
            ),
        ),
    ]
