# Generated by Django 5.0 on 2023-12-21 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0006_remove_client_arrival_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to="client.clientorder",
            ),
        ),
    ]
