# Generated by Django 5.0 on 2023-12-22 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0003_aircraftcharacteristic_aircraftdescription_and_more"),
        ("client", "0007_alter_client_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientorder",
            name="desired_aircraft",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="aircraft.aircraft",
            ),
        ),
    ]
