# Generated by Django 5.0 on 2023-12-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0008_clientorder_desired_aircraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="busy",
            field=models.BooleanField(default=False),
        ),
    ]
