# Generated by Django 5.0 on 2023-12-28 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0007_alter_aircraftcharacteristic_capacity_peoples"),
        ("client", "0009_client_busy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientorder",
            name="desired_aircraft",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="aircraft.aircraft",
            ),
        ),
    ]
