# Generated by Django 5.0 on 2023-12-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("aircraft", "0004_aircraft_busy"),
        ("available_cities", "0001_initial"),
        ("aviation_personnel", "0002_aviationpersonnel_busy"),
        ("client", "0009_client_busy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=None, null=True)),
                ("departure_date", models.DateField(default=None, null=True)),
                ("arrival_date", models.DateField(default=None, null=True)),
                (
                    "aircraft_id",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_aircraft",
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "arrival_city",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_arrival_city",
                        to="available_cities.availablecities",
                    ),
                ),
                (
                    "client_id",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_client",
                        to="client.client",
                    ),
                ),
                (
                    "departure_city",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_departure_city",
                        to="available_cities.availablecities",
                    ),
                ),
                (
                    "pilot",
                    models.OneToOneField(
                        default=None,
                        limit_choices_to={"role": "AviationPersonnel.Role.PILOT"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_pilot",
                        to="aviation_personnel.aviationpersonnel",
                    ),
                ),
                (
                    "pilot_assistant",
                    models.ForeignKey(
                        default=None,
                        limit_choices_to={
                            "role": "AviationPersonnel.Role.PILOT_ASSISTANT"
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_pilot_assistant",
                        to="aviation_personnel.aviationpersonnel",
                    ),
                ),
            ],
        ),
    ]
