# Generated by Django 5.0 on 2023-12-22 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0004_aircraft_busy"),
        ("aviation_personnel", "0003_aviationpersonnel_flight"),
        ("client", "0009_client_busy"),
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="aircraft_id",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="client_id",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="pilot",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="pilot_assistant",
        ),
        migrations.CreateModel(
            name="FlightComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aircraft_id",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_aircraft",
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "client_id",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_client",
                        to="client.client",
                    ),
                ),
                (
                    "pilot",
                    models.OneToOneField(
                        default=None,
                        limit_choices_to={"role": "AviationPersonnel.Role.PILOT"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_pilot",
                        to="aviation_personnel.aviationpersonnel",
                    ),
                ),
                (
                    "pilot_assistant",
                    models.ForeignKey(
                        default=None,
                        limit_choices_to={
                            "role": "AviationPersonnel.Role.PILOT_ASSISTANT"
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_pilot_assistant",
                        to="aviation_personnel.aviationpersonnel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flight",
            name="composition",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight",
                to="flight.flightcomposition",
            ),
        ),
    ]
