# Generated by Django 5.0 on 2023-12-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0004_aircraft_busy"),
        ("aviation_personnel", "0003_aviationpersonnel_flight"),
        ("flight", "0002_remove_flight_aircraft_id_remove_flight_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightcomposition",
            name="stewardess",
            field=models.ManyToManyField(
                default=None,
                limit_choices_to={
                    models.Q(("busy", False)),
                    models.Q(
                        ("role", "AviationPersonnel.Role.STEWARDESS"),
                        ("role", "AviationPersonnel.Role.ENGINEER"),
                        _connector="OR",
                    ),
                },
                null=True,
                related_name="flight_composition",
                to="aviation_personnel.aviationpersonnel",
            ),
        ),
        migrations.AlterField(
            model_name="flightcomposition",
            name="aircraft_id",
            field=models.OneToOneField(
                default=None,
                limit_choices_to={"busy": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flight_aircraft",
                to="aircraft.aircraft",
            ),
        ),
        migrations.AlterField(
            model_name="flightcomposition",
            name="pilot",
            field=models.OneToOneField(
                default=None,
                limit_choices_to={
                    "busy": False,
                    "role": "AviationPersonnel.Role.PILOT",
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flight_pilot",
                to="aviation_personnel.aviationpersonnel",
            ),
        ),
        migrations.AlterField(
            model_name="flightcomposition",
            name="pilot_assistant",
            field=models.ForeignKey(
                default=None,
                limit_choices_to={
                    "busy": False,
                    "role": "AviationPersonnel.Role.PILOT_ASSISTANT",
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flight_pilot_assistant",
                to="aviation_personnel.aviationpersonnel",
            ),
        ),
    ]
