# Generated by Django 5.0 on 2023-12-22 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aviation_personnel", "0003_aviationpersonnel_flight"),
        ("flight", "0003_flightcomposition_stewardess_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flightcomposition",
            name="stewardess",
        ),
        migrations.AddField(
            model_name="flightcomposition",
            name="stewards",
            field=models.ManyToManyField(
                default=None,
                limit_choices_to=models.Q(
                    ("busy", False),
                    models.Q(
                        ("role", "STEWARD"), ("role", "ENGINEER"), _connector="OR"
                    ),
                ),
                null=True,
                related_name="flight_composition",
                to="aviation_personnel.aviationpersonnel",
            ),
        ),
        migrations.AlterField(
            model_name="flightcomposition",
            name="pilot",
            field=models.OneToOneField(
                default=None,
                limit_choices_to={"busy": False, "role": "PILOT"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flight_pilot",
                to="aviation_personnel.aviationpersonnel",
            ),
        ),
        migrations.AlterField(
            model_name="flightcomposition",
            name="pilot_assistant",
            field=models.ForeignKey(
                default=None,
                limit_choices_to={"busy": False, "role": "PILOT_ASSISTANT"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flight_pilot_assistant",
                to="aviation_personnel.aviationpersonnel",
            ),
        ),
    ]
