# Generated by Django 5.0 on 2023-12-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aviation_personnel", "0003_aviationpersonnel_flight"),
        ("flight", "0005_rename_pilot_flightcomposition_pilot_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightcomposition",
            name="stewards",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                limit_choices_to=models.Q(
                    ("busy", False),
                    models.Q(
                        ("role", "STEWARD"), ("role", "ENGINEER"), _connector="OR"
                    ),
                ),
                null=True,
                related_name="flight_composition",
                to="aviation_personnel.aviationpersonnel",
            ),
        ),
    ]
