# Generated by Django 5.0 on 2023-12-28 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0007_alter_aircraftcharacteristic_capacity_peoples"),
        ("aviation_personnel", "0003_aviationpersonnel_flight"),
        ("client", "0010_alter_clientorder_desired_aircraft"),
        ("flight", "0006_alter_flightcomposition_stewards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightcomposition",
            name="aircraft_id",
            field=models.ForeignKey(
                default=None,
                limit_choices_to={"busy": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flight_aircraft",
                to="aircraft.aircraft",
            ),
        ),
        migrations.AlterField(
            model_name="flightcomposition",
            name="client_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flight_client",
                to="client.client",
            ),
        ),
        migrations.AlterField(
            model_name="flightcomposition",
            name="pilot_main",
            field=models.ForeignKey(
                default=None,
                limit_choices_to={"busy": False, "role": "PILOT"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flight_pilot",
                to="aviation_personnel.aviationpersonnel",
            ),
        ),
    ]
