# Generated by Django 5.0 on 2023-12-21 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0002_characteristicaircraft_descriptionaircraft_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AircraftCharacteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_pilot", models.BooleanField(default=True)),
                ("assistant_pilot", models.BooleanField(default=True)),
                ("staff_capacity", models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="AircraftDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="aircraft/")),
            ],
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="characteristic",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aircraft",
                to="aircraft.aircraftcharacteristic",
            ),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="description",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aircraft",
                to="aircraft.aircraftdescription",
            ),
        ),
        migrations.DeleteModel(
            name="CharacteristicAircraft",
        ),
        migrations.DeleteModel(
            name="DescriptionAircraft",
        ),
    ]
