# Generated by Django 5.0 on 2023-12-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0003_aircraftcharacteristic_aircraftdescription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="busy",
            field=models.BooleanField(default=False),
        ),
    ]
