# Generated by Django 5.0 on 2023-12-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0004_aircraft_busy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aircraftcharacteristic",
            name="assistant_pilot",
        ),
        migrations.RemoveField(
            model_name="aircraftcharacteristic",
            name="main_pilot",
        ),
        migrations.RemoveField(
            model_name="aircraftcharacteristic",
            name="staff_capacity",
        ),
        migrations.AddField(
            model_name="aircraftcharacteristic",
            name="capacity_peoples",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="aircraftdescription",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aircraftdescription",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="aircraft/"
            ),
        ),
    ]
