# Generated by Django 5.0 on 2023-12-25 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0005_remove_aircraftcharacteristic_assistant_pilot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aircraftdescription",
            name="image",
        ),
    ]
