# Generated by Django 5.0 on 2023-12-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AviationPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("second_name", models.CharField(max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PILOT", "Pilot"),
                            ("PILOT_ASSISTANT", "Pilot Assistant"),
                            ("STEWARD", "Steward"),
                            ("ENGINEER", "Engineer"),
                        ],
                        default=None,
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
