# Generated by Django 5.0 on 2023-12-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aviation_personnel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aviationpersonnel",
            name="busy",
            field=models.BooleanField(default=False),
        ),
    ]
