# Generated by Django 5.0 on 2023-12-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aviation_personnel", "0002_aviationpersonnel_busy"),
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aviationpersonnel",
            name="flight",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aviation_personnel",
                to="flight.flight",
            ),
        ),
    ]
